timeout: 1800s
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/pipi8:$TAG_NAME', '.']
    id: "build-pipi8-gcr"
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'asia.gcr.io/$PROJECT_ID/pipi8:$TAG_NAME']
    id: "push-pipi8-gcr"
tags:
  - "pipi8"  
