timeout: 1800s
steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["mod", "download"]
    id: "download-mod"
    env:
    - "GO111MODULE=on" 
    - "GOPATH=/go"
  - name: "gcr.io/cloud-builders/go"
    args: ["test", "-v", "./src/..."]
    id: "testing-pipi8"
    env:
    - "GO111MODULE=on" 
    - "GOPATH=/go"
tags:
  - "pipi8"
